env: local

log:
  level: debug # или "info", "warn", "error"

server:
  host: localhost
  port: "8080"

grpc:
  host: localhost
  port: "50051"

database:
  postgres:
    dsn: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
